### ISSUE TITLE
Order of projects in solution file affects build results

### ISSUE THREAD

**Issue by chtenb** [dotnet/msbuild#6198]
**Visual Studio Version**: 16.8.6

**Summary**:

The order in which projects are listed in the solution (.sln) file affects the results of the building process.  In my case, for some orders the build results are correct, and for others they are not.  It seems to me that this is a bug and the order of the projects should not matter at all, since the correct references are set and the derived build order seems valid in both cases.

Moreover, this problem only occurs when executing `MSBuild Rubjerg.Graphviz.sln` from the commandline (Developer Command Prompt for VS 2019).  From within Visual Studio the build always succeeds.  MSBuild version is the newest: `16.8.3.61104`.

**Context**:

I encountered this problem in a [very small opensource project](https://github.com/Rubjerg/Graphviz.NetWrapper), so it's easy for other people to reproduce.  The solution (`Rubjerg.Graphviz.sln`) consists of a single .NET library (`Rubjerg.Graphviz.csproj`) with a dependency on a single C++ library (`GraphvizWrapper.vcxproj`). The remaining projects are test projects.

**Steps to Reproduce**:

1. Check out the master branch of https://github.com/Rubjerg/Graphviz.NetWrapper
2. Restore the solution nuget packages: `nuget restore Rubjerg.Graphviz.sln`. 
3. Build the solution on a command prompt: `MSBuild Rubjerg.Graphviz.sln`.
4. Run the unittests on a command prompt: `packages\nunit.consolerunner\3.12.0\tools\nunit3-console.exe Rubjerg.Graphviz.Test\bin\x64\Debug\net48\Rubjerg.Graphviz.Test.dll`
5. Notice that the build succeeds and the tests pass. This is also indicated by the github workflow run on the latest commit of the master branch.

6. Clear all build artifacts (e.g. by running `git clean -dfx` in the root of the repository)
7. Change the solution file according to the diff shown in [this reproduction scenario](https://github.com/Rubjerg/Graphviz.NetWrapper/pull/33/files)
8. Repeat step 2, 3 and 4

**Expected Behavior**:
Succeeding build and succeeding unit tests.

**Actual Behavior**:
Notice that after step 2 the C++ DLLs are not present in the output directories of the managed projects.  If you execute step 3, you will notice the `System.DllNotFoundException`s.  This is also indicated by the github workflow run on [the reproduction scenario](https://github.com/Rubjerg/Graphviz.NetWrapper/pull/33).

**User Impact**:
All clients of our project run into this problem and have to meddle with the project order in the solution file to fix it.

**Comment by BenVillalobos** [comment]
Team Triage: Verify the repro works & gather some info, then add the untriaged label.

**Comment by BenVillalobos** [comment]
So I got it to repro and captured binlogs of each build: [solutions.zip](https://github.com/dotnet/msbuild/files/6394239/solutions.zip)

Unfortunately I couldn't repro after that. The tests seemed to work for me with the updated solution. Are you still seeing this with an updated msbuild?

It actually looks like you may have fixed the issue with https://github.com/Rubjerg/Graphviz.NetWrapper/pull/35/files?

The general idea here is you want to use ProjectReference to ensure certain projects are built first. When msbuild encounters a `.sln` file, it creates a metaproj file containing various `ProjectReferences`. The order of these references happen to be the same order as what it discovered in the `.sln` file.

**Comment by Chiel92** [comment]
I just re-ran the workflow in the reproduction PR for you, and still the same error occurs: https://github.com/Rubjerg/Graphviz.NetWrapper/pull/33/checks?check_run_id=2465253939

You should be able to reproduce by checking out that PR which is also referred to in the OP.

https://github.com/Rubjerg/Graphviz.NetWrapper/pull/35/files doesn't seem relevant, because the reproduction PR actually branches off from that commit.

![image](https://user-images.githubusercontent.com/1030961/116529306-1b0ce200-a8dd-11eb-9975-901c9e0ce2ff.png)

**Comment by BenVillalobos** [comment]
Using our latest preview `Microsoft (R) Build Engine version 16.10.0-preview-21253-02+fa96a2a81 for .NET Framework` I can't reproduce this behavior. There's a chance this could have been fixed in the meantime. Could you send the full output of `msbuild --version` so I can try on that specific version? Along with a specific commit hash (even if latest/master reproduces the behavior).

**Comment by Chiel92** [comment]
On github the build action reports:

```
> Run msbuild Rubjerg.Graphviz.sln /p:Configuration=Release

Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by v-codyguan** [comment]
@chtenb I tried to reproduce this issue on 16.8.6 with MSBuild 16.8.3+39993bd9d, and I couldn't reproduce this issue. Could you please help to check the repro steps in case I missed something? And to reproduce this issue, we tried to delete 'Rubjerg.Graphviz.Test.dll' manually from directories after step 3, then execute step 4, and we still couldn't get  this issue reproduce, does it make sense?
Repro steps:
1. Clone and check out the master branch of https://github.com/Rubjerg/Graphviz.NetWrapper
2. Open the solution to restore the packages.
3. Executing 'MSBuild Rubjerg.Graphviz.sln' on Developer Command Prompt for VS 2019.
4. Executing 'packages\nunit.consolerunner\3.12.0\tools\nunit3-console.exe'.
5. Executing 'git clean -dfx'.
6. Change the solution file.
7. Repeat step 4 and 5.
![image](https://user-images.githubusercontent.com/87402472/135246893-1191b0bf-e0d0-44ff-9592-ede089b0a602.png)

**Comment by chtenb** [comment]
@v-codyguan It looks like you forgot to pass the test.dll to the testrunner. The full test command of step 4 should be:

```
packages\nunit.consolerunner\3.12.0\tools\nunit3-console.exe Rubjerg.Graphviz.Test\bin\x64\Debug\net48\Rubjerg.Graphviz.Test.dll
```

Otherwise your steps look fine. I just repro'd with version `16.11.1+3e40a09f8`.

**Comment by v-codyguan** [comment]
Hi @chtenb thank you for sharing! We can reproduce this issue and contact our engineer in time. Thanks!

**Comment by BenVillalobos** [comment]
This one's a doozy. I don't fully understand the issue here, but I'm fairly certain it has to do with incremental builds. Marking as `needs-attention` for bug triage meeting.

Side note: Passing `/graph` to your msbuild invocation should resolve the issue. It did for me

**Comment by chtenb** [comment]
> Side note: Passing /graph to your msbuild invocation should resolve the issue. It did for me

Interesting, I didn't know about that parameter. Any reason why that isn't on by default?

**Comment by BenVillalobos** [comment]
> Any reason why that isn't on by default?

I don't know the details, just that there are many reasons unfortunately

You should be able to set up Command Line Arguments in the properties of your project. You could specify `/graph` there.

**Comment by BenVillalobos** [comment]
Dropping some context on this before it all disappears: Judging by the following symptoms:

- Changing order of build causes a failure
- /graph fixes it
- A build output isn't present at the right time

It's gotta be a build ordering issue, or that a certain project isn't copying the bits to the right place where another project may have been doing that (this is controlled by ReferenceOutputAssembly (see https://github.com/dotnet/msbuild/issues/7986 for notes on that).

So this could be a transitive reference issue, which I'm not too sure of a good solution for.

I think the simplest solution here is for your test project to reference your vcxproj and set `ReferenceOutputAssembly=true` for it so it can copy the output dll to the right place. This shouldn't cause overbuilds.

Airing out another workaround, you can create a target in your test project that looks for your cpp dll and copies it to where it needs to be in order for this test to run.

Sorry this one took a while to get back to 😅

**Comment by chtenb** [comment]
Thanks for coming back to this! Unfortunately the two workarounds you proposed are not more convenient for me than using a project order in the solution that works. Having all dependent projects reference this C++ project or add a custom target is unfeasible for large solutions and generally undesirable for a project that is meant to be pretty much plug-and-play.

> So this could be a transitive reference issue, which I'm not too sure of a good solution for.

Based on my anecdotal experience with build problems I'd definitely think so. Transitive copying behavior (or the lack thereof) has always caused headaches in my projects, especially when C++ projects were involved. 

I hoped that I had provided a tangible problem in this area with this github issue + example project, for which the solution or workaround hopefully could be made an example of for how to solve this nagging problem once and for all :)

**Comment by KirillOsenkov** [comment]
See if https://github.com/dotnet/msbuild/issues/9709 is related

**Comment by JaynieBai** [comment]
Tested this issue with MSBuild main branch merged https://github.com/dotnet/msbuild/pull/10836. Still has the error occasionally ----> System.DllNotFoundException : Unable to load DLL 'gvc.dll': The specified module could not be found
![Image](https://github.com/user-attachments/assets/ed6c1efe-1c2c-4f18-b889-49e5a2700d40)

**Comment by JanKrivanek** [comment]
Discussed offline - next steps:
* Collect binlogs of a build of a success and failed case
* Attach the binlogs to this bug
* Try to see if there is a difference between the two binlogs in how they copy the missing dll (gvc.dll)
* Put your findings (even if they are inconclusive) here, ping team for more help if needed

**Comment by JaynieBai** [comment]
This is success build log[msbuildSuccess.binlog.txt](https://github.com/user-attachments/files/18345322/msbuildSuccess.binlog.txt)

After changed the solution based on [this reproduction scenario](https://github.com/Rubjerg/Graphviz.NetWrapper/pull/33/files) and generated the failed binlog.
[msbuildFail.binlog.txt](https://github.com/user-attachments/files/18345326/msbuildFail.binlog.txt)

The differences are None items in the project Rubjerg.Graphviz don't include the binaries (including gvc.dll) generated form native project.

![Image](https://github.com/user-attachments/assets/a61a99e8-0cbe-4701-8210-3f1497265da4)

**Comment by SimaTian** [comment]
Hello, building on the work by @JaynieBai and thanks to pointers from @JanKrivanek I have prepared a fix pr for the original repository. This I did because I believe that this isn't a bug per-se, just a weird and somewhat poorly documented behavior of MSBuild.

For the completeness sake I'm copying a part of my analysis included in the PR:

Basically the issue is that if the item isn't within a target, it is resolved during Evaluation phase - e.g. as soon as the project file is [loaded into the MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/build-process-overview?view=vs-2022), but ProjectReference that is setting up the project dependency ordering is a Target so this happens:

 - MSBuild first loads a project (including evaluation) as specified by the .sln file
this is affected by the original project ordering change that resulted in the build failing
 - Then it evaluates the targets related to project references, [see here](https://github.com/dotnet/msbuild/blob/main/documentation/ProjectReference-Protocol.md).
   -specifically ResolveProjectReferences target
 - this builds the referenced projects - however the item is already processed by this point, resulting in an empty copy

By moving the item into a custom target and forcing order by setting AfterTargets, the files are moved correctly. Tests pass.

While I'm not completely sure I got everything correct, this is the conclusion I arrived after going through the MSBuildism blogpost, crosschecking with MSBuild documentation and experimenting on my machine.
It might be worth updating the documentation somewhere, if anyone has an idea where, it would be nice (since this behavior is a confluence of several different places)
